from pathlib import Path
import shutil,zipfile,json
root=Path(__file__).resolve().parents[2];ep=Path(__file__).resolve().parent;pack=root/'03_SCRIPTS/00_TEMPLATES/characters/commentary_duo_v1';dst=ep/'remotion/public/exported';dst.mkdir(exist_ok=True)
for f in (pack/'exports').glob('*.png'):shutil.copy2(f,dst/f.name)
with zipfile.ZipFile(ep/'commentary_duo_32sprites.zip','w',zipfile.ZIP_DEFLATED) as z:
 for f in sorted((pack/'exports').glob('*.png')):z.write(f,f.name)
 z.write(pack/'README.md','README.md')
(ep/'preview.html').write_text('''<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>そば屋解説｜たこさんとやめ太郎</title><style>
:root{font-family:system-ui,sans-serif;color:#303a3b;background:#f3f0e8}body{max-width:1140px;margin:38px auto;padding:0 24px}h1{font-size:28px;margin:6px 0 18px}p{line-height:1.8}video{width:100%;border-radius:12px;background:#e8e5de}.label{font-size:13px;letter-spacing:.15em;color:#77746b}a{color:#6a4e89}nav{display:flex;gap:18px;margin:18px 0 46px;flex-wrap:wrap}.controls{display:flex;gap:20px;align-items:center;flex-wrap:wrap;margin:20px 0}button,select{font:inherit;padding:9px 15px;border:1px solid #bcb7ac;border-radius:8px;background:white;color:#394343;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.card{background:#e9e5dd;border-radius:12px;padding:12px;text-align:center}.portrait{height:270px;position:relative}.portrait img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain}.card b{display:block;margin-top:8px;font-weight:600}h2{font-size:24px;margin-top:35px}.fine{font-size:13px;color:#77746b}body.dark .card{background:#383b42}body.dark .card b{color:#f7f4ea}@media(max-width:700px){.grid{grid-template-columns:repeat(2,1fr)}.portrait{height:230px}h1{font-size:24px}}</style>
<div class="label">窓際族物語</div><h1>そば屋って、どんな人？</h1><video controls playsinline preload="metadata" src="final_remotion_sobaya.mp4"></video><p>たこさんとやめ太郎が、そば屋の人柄と窓際での出来事を解説。全8種類の表情・ポーズ、口パク、たこさんのまばたきを盛り込みました。音声あり・BGMなし。</p><nav><a href="final_remotion_sobaya.mp4" download>動画を保存</a><a href="commentary_duo_32sprites.zip" download>透過PNG・32枚をまとめて保存</a><a href="#gallery">差分を見る</a></nav>
<h2 id="gallery">表情・ポーズの差分</h2><div class="controls"><label>口 <select id="mouth"><option value="closed">閉じる</option><option value="open">開く</option><option value="animate">口パクを再生</option></select></label><label><input id="flip" type="checkbox"> 左右反転</label><label><input id="dark" type="checkbox"> 暗い背景で確認</label></div><p class="fine">各キャラ8種類 × 口閉じ・口開き＝32枚。画像をクリックするとPNGを開きます。</p><div id="cards"></div><script>
const moods=[['normal','通常'],['happy','喜び'],['surprise','驚き'],['worry','困り'],['bored','呆れ'],['angry','怒り'],['sad','落ち込み'],['smug','得意げ']];
for(const [who,label] of [['takosan','たこさん'],['yametaro','やめ太郎']]){let h=document.createElement('h2');h.textContent=label;cards.append(h);let grid=document.createElement('div');grid.className='grid';for(const [mood,text] of moods){let card=document.createElement('div');card.className='card';card.dataset.who=who;card.dataset.mood=mood;card.innerHTML=`<a target="_blank" class="png"><div class="portrait"><img class="closed" src="remotion/public/exported/${who}_${mood}_closed.png"><img class="open" style="display:none" src="remotion/public/exported/${who}_${mood}_open.png"></div></a><b>${text}</b>`;grid.append(card);}cards.append(grid);}
let tick=0;function update(){const state=mouth.value==='animate'?(tick++%3?'open':'closed'):mouth.value;for(const card of document.querySelectorAll('.card')){card.querySelector('.closed').style.display=state==='closed'?'block':'none';card.querySelector('.open').style.display=state==='open'?'block':'none';card.querySelector('.portrait').style.transform=flip.checked?'scaleX(-1)':'';card.querySelector('.png').href=`remotion/public/exported/${card.dataset.who}_${card.dataset.mood}_${state}.png`;}document.body.classList.toggle('dark',dark.checked);}mouth.onchange=flip.onchange=dark.onchange=update;update();setInterval(()=>{if(mouth.value==='animate')update()},180);
</script></html>''')
print('pack',len(list(dst.glob('*.png'))),'files')
