import React from 'react';
import {Img,staticFile} from 'remotion';
import {useDiagramTiming} from './DiagramTiming';
const gold='#c9b682';
export const LegendPlate:React.FC<{kind:'atlantis'|'area51'}>=({kind})=><div style={{width:780,height:360,position:'relative'}}><Img src={staticFile(`${kind}_v6.png`)} style={{width:780,height:360,objectFit:'cover'}}/><div style={{position:'absolute',bottom:16,left:18,background:'#07111cdb',padding:'10px 16px',fontSize:20}}>{kind==='atlantis'?'海に沈んだ文明の伝説 ／ 想像復元図':'秘密の航空機試験施設 ／ イメージ図'}</div></div>;
export const CommonPointFigure:React.FC<{kind:'water'|'secret'}>=({kind})=>{
 const {show}=useDiagramTiming();const water=kind==='water';const cards=water?[['atlantis_v6.png','アトランティス','海の中','伝説の想像復元'],['evidence_ruins.jpg','SOBAYAの容器','液体の中','受領記録']]:[['area51_v6.png','エリア51','中身がよく分からない','施設のイメージ'],['sobaya_silhouette_v2.png','SOBAYA','中身がよく分からない','目撃証言による輪郭図']];
 return <div style={{width:780,height:360,position:'relative'}}><div style={{display:'flex',justifyContent:'space-between'}}>{cards.map(([file,label,point,source])=><div key={label} style={{width:355}}><div style={{fontSize:25,marginBottom:10}}>{label}</div><div style={{position:'relative',height:190,background:'#7d8a80'}}><Img src={staticFile(file)} style={{width:355,height:190,objectFit:file.includes('silhouette')?'contain':'cover'}}/><div style={{position:'absolute',bottom:6,left:7,fontSize:15,background:'#09121cdd',padding:'4px 7px'}}>{source}</div></div><div style={{opacity:show(water?(file.includes('atlantis')?'water_left':'water_right'):'secret_result'),fontSize:24,color:gold,marginTop:14}}>{point}</div></div>)}</div><div style={{position:'absolute',bottom:1,width:'100%',opacity:show(water?'water_result':'secret_result'),borderTop:`1px solid ${gold}`,paddingTop:13,fontSize:25,color:gold}}>共通点：{water?'どちらにも、水がある':'どちらも、よく分からない'}</div></div>;
};
export const FilmReport:React.FC=()=> {const {show}=useDiagramTiming();return <div style={{width:780,height:360,display:'flex',alignItems:'center',gap:36}}><div style={{width:275,flexShrink:0}}><div style={{fontSize:19,color:'#9faaa7',marginBottom:18}}>研究に使用した資料</div><div style={{border:'7px solid #74827f',borderRadius:7,background:'#0e1921',height:160,display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',gap:16}}><svg width="48" height="42"><path d="M6 2L44 21L6 40Z" fill={gold}/></svg><div style={{opacity:show('film_machine'),fontSize:23,color:gold}}>テレビで確認</div></div><div style={{width:15,height:19,background:'#74827f',margin:'0 auto'}}/><div style={{width:100,height:5,background:'#74827f',margin:'0 auto'}}/><div style={{fontSize:19,marginTop:17,color:'#9faaa7'}}>視聴記録を報告書へ添付</div></div><div style={{flex:1,textAlign:'left',borderTop:`1px solid ${gold}`,borderBottom:`1px solid ${gold}`,padding:'20px 0'}}><div style={{fontSize:18,color:'#a6b1ac',letterSpacing:2}}>霜重研究員・比較資料 01</div><div style={{opacity:show('film_title'),fontSize:34,color:gold,margin:'17px 0'}}>『天空の城ラピュタ』</div><div style={{fontSize:23,lineHeight:1.95}}><span style={{opacity:show('film_title')}}>資料種別：アニメ映画</span><br/><span style={{opacity:show('film_machine')}}>確認事項：古い機械が動いた</span><br/><span style={{opacity:show('film_impression')}}>感想：すごかった</span></div></div></div>;
};
export const SignalFigure:React.FC=()=> {
 const {show,frame,at}=useDiagramTiming();const shake=frame>=at('signal_shake')&&frame<at('signal_response')?Math.sin((frame-at('signal_shake'))*.5)*4:0;
 return <div style={{width:780,height:360}}><svg width="780" height="265" viewBox="0 0 780 265"><g transform={`translate(${shake} 0)`}><g fill="none" stroke="#a6b1ac" strokeWidth="3"><ellipse cx="120" cy="52" rx="46" ry="13"/><path d="M74 52V180C74 200 166 200 166 180V52"/><ellipse cx="120" cy="180" rx="46" ry="13"/><path opacity={show('signal_shake')} d="M52 91L34 112L52 133M188 91L206 112L188 133"/></g><text x="120" y="128" fill="#d5ddd8" textAnchor="middle" fontSize="23">未開封</text></g><g opacity={show('signal_sound')}><g fill="none" stroke="#a6b1ac" strokeWidth="3"><path d="M251 122H313L300 110M313 122L300 134"/><path d="M337 123H360L370 93L382 151L395 108L409 140L424 88L438 149L452 113L466 123H505"/></g><text x="421" y="239" fill={gold} textAnchor="middle" fontSize="25">ちゃぷちゃぷ</text><text x="421" y="62" fill="#98a7a4" textAnchor="middle" fontSize="17">反応の模式図</text></g><g opacity={show('signal_response')}><path d="M529 122H589L576 110M589 122L576 134" fill="none" stroke="#a6b1ac" strokeWidth="3"/><g fill={gold} fontSize="25" textAnchor="middle"><text x="681" y="110">地球人への</text><text x="681" y="146">応答と解釈</text></g></g><text opacity={show('signal_shake')} x="120" y="239" fill={gold} textAnchor="middle" fontSize="25">円筒を振る</text></svg><div style={{opacity:show('signal_conference'),borderTop:`1px solid ${gold}`,paddingTop:18,color:gold,fontSize:25}}>中身は未確認のまま、国際会議へ</div></div>;
};
